### ISSUE TITLE
how long it takes on './src/eval.sh yago_ko_0.4 61'

### ISSUE THREAD

**Issue by loveJasmine** [GentleZhu/HEER#6]
i7 6700, 16G, gtx970 4G is my device

**Comment by GentleZhu** [comment]
YaGo dataset takes ~400 MB GPU memory, DBLP will use about 3.5 GB memory. It takes less than one hour on our machine with GTX 1080.

**Comment by loveJasmine** [comment]
after 4 hours on my machine, it undone yet.
however, it show only user 1.2G gpu memeory， but takes almost all CPU memory(16G)

**Comment by GentleZhu** [comment]
You need to train it before you can test it. Remeber to download the pre-trained embedding and put it under the intermediate folder.
