### ISSUE TITLE
Can HEER be applied to graph with attribute?

### ISSUE THREAD

**Issue by Ailing-Zou** [GentleZhu/HEER#9]
Hi,
Can HEER be applied to graph with attribute?
My application is directed, weighted graph with attribute.

**Comment by ysyushi** [comment]
It can, but it is not designed for attributed graphs, so it may not achieve its best performance on these graphs. The way it applies is to consider each attribute as a different node type.

**Comment by Ailing-Zou** [comment]
Ok, thank you for your kind help!

**Comment by Crystalsudo** [comment]
Ok, thank you for your kind help!
